---
title: "Summary"
author: "Tyler Peckenpaugh"
date: "3/5/2019"
output:
  pdf_document: default
  html_document:
    highlight: tango
    theme: journal
---

# 3-level prosodic pattern

Placeholder


## Full model
## Without interacton term
## Only "gp-sensitive"
### With interaction
## Without interaction

<!--chapter:end:all.Rmd-->


# Logit models

Placeholder


## Predicting PP1 as strongest or only break

<!--chapter:end:bin.Rmd-->


# crosstab

Placeholder


## Both readings

<!--chapter:end:bin2.Rmd-->


# Crosstabs

Placeholder


## Struggle 
## V break
## PP1 break
## OBJ break
## Question intonation hit/miss
## Predicting PP1
## Predicting PP1 as strongest or only break

<!--chapter:end:binary-and-categorical.Rmd-->


# Inter-item timing

Placeholder


## Description and cleanup
## Distribution of IRTs, all participants
## Missing data and attrition
## Group sizes after attrition
## Distribution of experimental item IRT after attrition
## Mean and SD of winsorized IRT by condition
## Item and subject variation
## Number of participants who show predicted pattern
## Number of items that show predicted pattern
## Regression analyses
## PP1 Break
## OBJ Break
## PP1 Break by &plusmn;Q
## OBJ Break by &plusmn;Q
## PP1 Break by &plusmn;GP
## OBJ Break by &plusmn;GP

<!--chapter:end:handout.Rmd-->


#   tufte_features: ["fonts", "italics"]

Placeholder


## IRT measurement
## Difference in delay across paired readings

<!--chapter:end:irt-data.Rmd-->


# Inter-item timing

Placeholder


## Group sizes after attrition
### Avaialability of experimental item IRT after attrition
## Distribution of experimental item IRT after attrition
## Number of participants who show predicted pattern
## Number of items that show predicted pattern

<!--chapter:end:irt-desc.Rmd-->


# Inter-item timing

Placeholder


## Description and cleanup
## Distribution of IRTs, all participants
## Missing data and attrition
## Group sizes after attrition
## Distribution of experimental item IRT after attrition
## Mean and SD of winsorized IRT by condition
## Item and subject variation
## Number of participants who show predicted pattern
## Number of items that show predicted pattern
## Regression analyses
## GEE Analyses
## GEE Analyses

<!--chapter:end:irt-desc2.Rmd-->


# Inter-item timing

Placeholder


## Description and cleanup
## Distribution of IRTs, all participants
## Missing data and attrition
## Group sizes after attrition
## Distribution of experimental item IRT after attrition
## Mean and SD of winsorized IRT by condition
## Item and subject variation
## Number of participants who show predicted pattern
## Number of items that show predicted pattern
## Regression analyses

<!--chapter:end:irt-desc3-notoc.Rmd-->


# Inter-item timing

Placeholder


## Description and cleanup
## Distribution of IRTs, all participants
## Missing data and attrition
## Group sizes after attrition
## Distribution of experimental item IRT after attrition
## Mean and SD of winsorized IRT by condition
## Item and subject variation
## Number of participants who show predicted pattern
## Number of items that show predicted pattern
## Regression analyses

<!--chapter:end:irt-desc3.Rmd-->


# Inter-item timing analyses

Placeholder


## Mean and SD of IRT by condition
## boxplot of mean inter-item time by condition
## All participants
### Full model
### Full model (natural log)
### Full model (common log)
### Full model (inverse)
### Full model (squared)
### Without interacton 
## Only "gp-sensitive"
### With interaction
### Without interaction
## Homogeneity of variance
### All Ps
### All Ps (natural log)
### All Ps (squared)
### All Ps (inverse)
### All Ps (Log10)
### Only GP-sense
## Normal distribution of residuals
### All participants
### All participants (Natural log)
### All participants (Log 10)
### All participants (Inverse)
### All participants (Squared)
### Only GP-sensitive participants
## Linearity
### All Ps
### All Ps (nautral log)
### All Ps (log10)
### All Ps (squared)
### All Ps (Inverse)
### GP-sensitive only

<!--chapter:end:lmer-combined-winsorized.Rmd-->


# Inter-item timing analyses

Placeholder


## Mean and SD of IRT by condition
## boxplot of mean inter-item time by condition
## All participants
### Full model
### Full model (natural log)
### Full model (common log)
### Full model (inverse)
### Full model (squared)
### Without interacton 
## Only "gp-sensitive"
### With interaction
### Without interaction
## Homogeneity of variance
### All Ps
### All Ps (natural log)
### All Ps (squared)
### All Ps (inverse)
### All Ps (Log10)
### Only GP-sense
## Normal distribution of residuals
### All participants
### All participants (Natural log)
### All participants (Log 10)
### All participants (Inverse)
### All participants (Squared)
### Only GP-sensitive participants
## Linearity
### All Ps
### All Ps (nautral log)
### All Ps (log10)
### All Ps (squared)
### All Ps (Inverse)
### GP-sensitive only

<!--chapter:end:lmer-combined.Rmd-->


# Inter-item timing analyses

Placeholder


## boxplot of mean inter-item time by condition
## All participants
### Full model
### Without interacton 
## Only "gp-sensitive"
### With interaction
### Without interaction
## Homogeneity of variance
### All Ps
### Only GP-sense
## Normal distribution of residuals
### All participants
### Only GP-sensitive participants
## Linearity
### All Ps
### GP-sensitive only

<!--chapter:end:lmer.Rmd-->


# Inter-item timing analyses

Placeholder


## histograms
## Mean and SD of winsorized IRT by condition
## Means by conidtion and item/subject
### Number of participants who show predicted pattern
### Number of items that show predicted pattern
## boxplot of mean inter-item time by condition

<!--chapter:end:lmer2.Rmd-->


# Inter-item timing analyses

Placeholder


## histograms
## Mean and SD of winsorized IRT by condition
## Means by conidtion and item/subject
### Number of participants who show predicted pattern
### Number of items that show predicted pattern
## boxplot of mean inter-item time by condition

<!--chapter:end:lmer3.Rmd-->


# Inter-item timing analyses

Placeholder


## boxplot of mean inter-item time by condition
## All participants
### Full model
### Without interacton 
## Only "gp-sensitive"
### With interaction
### Without interaction
## Homogeneity of variance
### All Ps
### Only GP-sense
## Normal distribution of residuals
### All participants
### Only GP-sensitive participants
## Linearity
### All Ps
### GP-sensitive only

<!--chapter:end:lmerInverse.Rmd-->


# Inter-item timing analyses

Placeholder


## boxplot of mean inter-item time by condition
## All participants
### Full model
### Without interacton 
## Only "gp-sensitive"
### With interaction
### Without interaction
## Homogeneity of variance
### All Ps
### Only GP-sense
## Normal distribution of residuals
### All participants
### Only GP-sensitive participants
## Linearity
### All Ps
### GP-sensitive only

<!--chapter:end:lmerLn.Rmd-->


# Inter-item timing analyses

Placeholder


## boxplot of mean inter-item time by condition
## All participants
### Full model
### Without interacton 
## Only "gp-sensitive"
### With interaction
### Without interaction
## Homogeneity of variance
### All Ps
### Only GP-sense
## Normal distribution of residuals
### All participants
### Only GP-sensitive participants
## Linearity
### All Ps
### GP-sensitive only

<!--chapter:end:lmerLog10.Rmd-->


# Logit models

Placeholder



<!--chapter:end:logit.Rmd-->


# Crosstabs

Placeholder


## Struggle 
## V break
## PP1 break
## OBJ break
## Question intonation hit/miss

<!--chapter:end:pros-xtabs.Rmd-->


# Breaks by condition

Placeholder


## PP1 Break
## OBJ Break
## PP1 Break by &plusmn;Q
## OBJ Break by &plusmn;Q
## PP1 Break by &plusmn;GP
## OBJ Break by &plusmn;GP

<!--chapter:end:prosody-data.Rmd-->


# Breaks by condition

Placeholder


## PP1 Break
## OBJ Break
## PP1 Break by &plusmn;Q
## OBJ Break by &plusmn;Q
## PP1 Break by &plusmn;GP
## OBJ Break by &plusmn;GP

<!--chapter:end:prosody-desc.Rmd-->


# Logit models

Placeholder


## Predicting PP1 as strongest or only break

<!--chapter:end:prosody.Rmd-->


# Breaks by condition

Placeholder


## PP1 Break
## OBJ Break
## PP1 Break by &plusmn;Q
## OBJ Break by &plusmn;Q
## PP1 Break by &plusmn;GP
## OBJ Break by &plusmn;GP

<!--chapter:end:prosoy-data.Rmd-->


# Excluding items

Placeholder


## Generalized Estimating Equation
## GEE Analyses

<!--chapter:end:salvage-irt-desc3.Rmd-->


# 3-level prosodic pattern

Placeholder


## Full model
## Without interacton 
## Only "gp-sensitive"
### With interaction
## Without interaction

<!--chapter:end:summary.Rmd-->

