---
title: "_validityprep"
author: "Tyler Peckenpaugh"
date: "5/26/2019"
output: html_document
---
```{r}
library(irr)
dr<-read_csv("../csvs/src/DR-V.csv") 
sp<-read_csv("../csvs/src/SP-V.csv") 
main<-read_csv("export/prosody_data.csv") %>% subset(UID %in% dr$UID) 

vals = c("V","OBJ","PP1","STRONG","WEAK","STRUG","STRUG_START","QI")
logicals = c("V","OBJ","PP1","STRUG","QI")
suffixes=c("-dr","-sp")


for (col in logicals){
  main[[col]] <- ifelse(main[[col]] == TRUE, "YES", 
                 ifelse(main[[col]] == FALSE, "NO", 
                        main[[col]]
                 ))
}

drsp<-merge(dr,sp,by="UID",suffixes=suffixes)
all<-merge(drsp,main,by="UID")
all[is.na(all)] <- "NONE"

write_csv2(all,"drafts/export/prosody_validity.csv")
```

```{r}
for(suf in c(suffixes,"")){
  all[[paste0("pattern",suf)]] <-
  ifelse(
    all[[paste0("PP1",suf)]] == "NO" & all[[paste0("OBJ",suf)]] == "NO", 
    "NONE", 
    ifelse(
      all[[paste0("PP1",suf)]] == "YES" & all[[paste0("OBJ",suf)]] == "NO",
      "PP1",
      ifelse( 
        all[[paste0("PP1",suf)]] == "NO" & all[[paste0("OBJ",suf)]] == "YES",
        "OBJ",
        ifelse(
          all[[paste0("STRONG",suf)]] == "PP1" | all[[paste0("WEAK",suf)]] == "OBJ",
          "PP1 > OBJ",
          ifelse(
            all[[paste0("STRONG",suf)]] == "OBJ" | all[[paste0("WEAK",suf)]] == "PP1",
            "OBJ > PP1",
            "BOTH"
          )
        )
      )
    )
  )
}

```