```{r echo=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	fig.height = 3,
	message = FALSE,
	warning = FALSE
)
```

\raggedright
# Abstract {-}

\huge Prepositional phrase attachment ambiguities in declarative and interrogative contexts: Oral reading data\par




\normalsize Certain English sentences exhibiting temporarily ambiguous, e.g. *she had planned to cram the paperwork in the drawer into her briefcase*, have been reported to be prone to mis-parsing of a kind is typically called a “garden path.” The phenomenon stems from the temporary ambiguity of the first prepositional phrase *in the drawer* (PP1), which is expected to initially be interpreted as the goal argument of *cram*. PP1 is then disambiguated against the expected parse due to the second prepositional phrase *into her briefcase* (PP2) being incompatable with any interpretation other than as the goal of *cram* and thus necessarily supplanting PP1's initial position, such that PP1 must be reanalyzed as a modifier of the object NP *the paperwork*. Intuitively, interrogative versions, e.g., *had she planned to cram the paperwork in the drawer into her briefcase?* are easier to process than otherwise identical declaratives.  The study presented here represents an attempt to find a behavioral correlate of this intuitive difference in processing difficulty. 

The experiment employs the Double Reading Paradigm (Fodor, Macaulay, Ronkos, Callahan, and Peckenpaugh, 2019). Participants were asked to read aloud a visually presented sentence twice, first without taking any time at all to preview the sentence content (Reading 1), and then again after unlimited preview (Reading 2). The basic experimental items had been created in a 2 x 2 design with one factor being Speech Act (interrogative/Q vs. declarative/D) and the other being PP2 Status, i.e., PP2 was either a PP which could only be an argument of the verb (Arg) or else one which cpi;d ne interpreted as a modifier (Mod) of the preceding phrase. The PP2 Status factor can be thought of as a distinction between difficult to process sentences like  Arg items (whether declarative or interrogative) illustrated above, and corresponding Mod forms that pose no particular processing difficulty such as, *she had planned to cram the paperwork in the drawer of her filing cabinet/had she planned to cram the paperwork in the drawer of her filing cabinet?*

Participants' recordings of Reading 1 and Reading 2 were subjected to prosodic coding by a linguist who was naive to the research questions. Those descriptions were then analyzed statistically to extract the significant prosodic boundary patterns as a function of Speech Act and PP2 Status.

Another analysis was conducted which concerned the amount of time the participants spent silently studying a sentence after Reading 1 to be sure they understood it before reading the sentence aloud again (Reading 2). The time between readings is referred to as the inter-reading time (IRT). It was assumed that a longer IRT signified greater processing difficulty of the sentence. Thus, IRT was hypothesized to provide a behavioral correlate of the intuition under examination. If a correlate had been found, it would have taken the form of an interaction between the two factors such that the amount by which IRT was greater for Arg sentences than for Mod sentences was longer for declaratives than for interrogatives. Ultimately, however, no statistically significant interaction between Speech Act and PP2 Status was found.

Further studies are proposed for seeking behavioral evidence of the informal intuition motivating this research. Also offered are explanations for why the intuition is apparently so strong for some speakers, and why, if so, the intuition is not reflected in IRT. Ancillary findings suggest that interrogatives are more difficult to process than declaratives in general, as has been reported, and that inter-reading time (IRT) can be used as a measure of processing difficulty.


# Acknowledgements {-}

The completion of this dissertation would have been impossible without the help of my friends, family, colleagues, and most of all, my committee of advisers. The timing of its completion could not have been more difficult for me or for the chair of my committee, Janet Fodor. To Janet, I say: thank you for your endurance, your wisdom, and your patience. 

Much of the burden that stemmed from the difficult timing fell onto the plate of my second adviser, Dianne Bradley. To Dianne, I say: thank you for your tireless effort, your support, and your encouragement.
	
It is stereotypically believed, far and wide, that linguists are bad at math. This shortcoming is true of me, if not all my fellows. The burden of this fell mostly upon my third adviser, Martin Chodorow. To Martin, I say: thank you for your kindness, your teaching, and your forgiveness.

I am also indebted in particular to my closest friend and partner, Tally Callahan. She endured many restless nights, grumpy days, unhinged panic attacks, and worse. Thank you, Tally, for helping me see this through.

In a more practical way, I am indebted to Eva Fernandez and Nathacia Lucena. Without them, data collection would have been infinitely more difficult. Thank you for the use of your lab! And, to Bill Haddican, for his advice on handling the syntax of the construction I studied.

I also want to thank my parents and my sister for the love and encouragement. It was an extremely difficult time for us as a family, and especially for my father. For your understanding of the limitations on my time that writing this dissertation entailed, thank you. 

Special thanks to my brother-in-law, Kurtiss Hare, for his help on the Python coding I did. Also, thank you to my friends Corbin Neuhauser and Kathryn O’Shields for their input on the matters at large, as well as their camaraderie. Likewise, Burke Blackman, Pablo Gonzalez, and Michael Madden, for friendship and encouragement. 

Last, but not least, Laurie Bruce: thank you for going above and beyond when I asked for a favor!

\pagebreak