```{r echo=F}
knitr::opts_chunk$set(
  echo=FALSE, 
  warning=FALSE, 
  message=FALSE, 
  fig.height = 3, 
  fig.pos="H"
)
```
\pagenumbering{arabic}
\definechangesauthor{TJP}
\definechangesauthor{JDF}
<!--
%Dissertation introduction
%This is the first content section
%Previous section: Front matter
%Following section: Background
-->
# Introduction and background

\comment{example of what markup means; by default changes are based on discussion--superscript initials "TJP"" indicate changes that have not been discussed}
\replaced{added text}{deleted text}

This paper presents a study on human sentence processing, or parsing, and on the parsing of a particular sort of ambiguity. Parsing is assumed to be the projection of structure by a reader or listener over a string \added{of words} (which \deleted{obviously} lacks inherent structure). Following the \deleted{sort of} model\added{s} of parsing \replaced{developed}{put forward} by, e.g., @kimball1973seven, @frazier1978sausage, and @frazier1996construal, this study assumes that parsing is done online \added{, (i.e., during listening to or reading the word string)} \replaced{with the aim}{and} that most material \replaced{is}{must be} incorporated into the structure being built as soon as it is encountered. This can lead to mis-parses, where the parser has guessed wrong about how to incorporate a \deleted{given phrase with a} temporarily ambiguous \replaced{phrase in the input, which becomes apparent when subsequent}{structure, and then encounters} material \replaced{is encountered which}{that} cannot be incorporated into the \replaced{resulting}{current} structure. \added{This sort of pars\replaced{ing}{er} crash is called a "garden path."} When \replaced{it}{this} happens, the parser must reanalyze the material that had so far been processed, in order to \replaced{arrive at a}{come upa} structure that can accommodate both the new and \added{the} old material grammatically. \deleted{This sort of parser crash is called a garden path.}

\added{In short:}"Garden path\added{"} effects\deleted{”} occur when a temporarily ambiguous sentence resolves in such a way that the structure initially preferred by the parser is incompatible with how the sentence actually continues. These parsing errors have traditionally been attributed to structurally-\replaced{driven}{focused} parsing preferences [@kimball1973seven; @frazier1978sausage; @Frazier1979-pb] \replaced{which}{that} ignore semantic content on the first pass. @Frazier1979-pb formulates several of these \added{structural preferences}, including the following two which are widely accepted in one form or another:

  (@MinAtt) *Minimal attachment*
  Attach incoming material into the phrase-marker being constructed using the fewest nodes consistent with the well-formedness rules of the language under analysis [@Frazier1979-pb p.24]
  
  (@LateClo) *Late closure*
  When possible, attach incoming material into the clause currently being parsed [@Frazier1979-pb p.20]

Because these strategies ignore semantic and pragmatic plausibility and the parser typically does not know what material might \replaced{occur}{be} further on in the \added{word} string, mis-parses at temporarily ambiguous regions can occur\replaced{.}{, resulting in garden paths.} Minimal Attachment (MA) is important to \replaced{the present}{this} study and will be revisited \replaced{later on.}{in Section} \@ref(mech).

An example is the commonly studied garden path sentence, “The horse raced past the barn fell” [@bever1970]. Here, the initial parse incorrectly assumes that the matrix subject is the unmodified NP *the horse*, per Minimal Attachment, and takes the matrix verb to be *raced*, as in the sentence, *The horse raced past the finish line*.

  (@hbf) The horse raced past the barn fell\added{.} [@bever1970]
      a) [~S~ [~NP~ The horse] [~VP~ raced past the barn]] &emsp; ??? &emsp; [~VP~ fell]
      b) [~S~ [~NP~ The horse raced past the barn] [~VP~  fell]]

An attempted parse resulting in structure (@hbf a) crashes, as it is not possible to incorporate the final word *fell* in a grammatical way. Reanalysis is required, with the grammatical parse being (@hbf b) where the matrix subject is *the horse raced past the barn*, a noun phrase (NP) \replaced{in which \em{the horse} is modified by}{containing} a reduced relative clause *raced past the barn*. \replaced{Then}{Thus} *fell* can be incorporated as the matrix verb \added{of the sentence}, with a structure comparable to, *The horse (that was) raced past the barn was hungry*.

The study \deleted{being} reported \added{in this dissertation} is concerned with \deleted{certain} sentences that contain a temporarily ambiguous prepositional phrase (PP1), followed by another (PP2) which causes the \replaced{initial}{expected} parse to crash. Specifically, it is expected that PP1 in \added{an example such as} (@cramiGPy) will initially be interpreted as the goal of \em{cram}, but that parse will fail when it is realized that PP2 \added{(\em{in his briefcase})} cannot plausibly modify \em{drawer}. \added[id=TJP]{Instead, PP1 will have to modify \em{paperwork} so that PP2 can be the goal argument of \em{cram}.}

(@cramiGPy) He had planned to cram the paperwork [~PP1~ in the drawer] [~PP2~ in his briefcase].

(@cramiGPn) He had planned to cram the paperwork [~PP1~ in the drawer [~PP2~ of his filing cabinet]].

This contrasts with the \deleted{similar} sentence in (@cramiGPn)\added{,} where PP2 can plausibly modify *drawer* and so the parse where \added{the PP1} *in the drawer* is the goal argument is accept\replaced{able,}{ed} and *of his filing cabinet* is incorporated as a modifier within \replaced{it}{PP1}.



## Motivations for the current study {#obs}

The current study was initially motivated by \replaced{a phenomenon}{an observation} discovered by Janet Dean Fodor and Dianne Bradley, and originally reported in @qp2. That observation \replaced{wa}{i}s that a garden path sentence like (@cramiGPy) repeated here as (@dec) is, for whatever reason, not as difficult to process when presented as an interrogative, as in (@intr), rather than a\added{s a} declarative.

  (@dec) He had planned to cram the paperwork \deleted{[~PP1~} in the drawer\deleted{] [~PP2~} in his briefcase\deleted{]}.

  (@intr) Had he planned to cram the paperwork \deleted{[~PP1~} in the drawer\deleted{] [~PP2~} in his briefcase\deleted{]}?

@qp2 attempted to find a behavioral correlate of this intuition by \replaced{examining}{looking at} variation in reading time \replaced{for}{of} sentence\added{s} like (@dec) and (@intr), but the results were inconclusive. The current study continues that line of research by \replaced{testing}{looking at} similar sentences, while also attempting to control \replaced{certain}{additional} factors that may have led to @qp2's inconclusive results. One such concern is that (@dec) relies on the \added{practical} implausibility of a drawer within a briefcase, i.e., \added{on} real world knowledge, in order to disambiguate\deleted{d} the appropriate attachment sites for PP1 and PP2. Real world knowledge and beliefs \replaced{about}{of} what is or is not plausible \added{likely} var\replaced{y}{ies} between speakers and \added{so} may not always be \replaced{effective}{reliable} as a trigger for reanalysis. The current study makes use of carefully constructed sentences (the criteria by which they were constructed \replaced{are}{is} detailed in Section \@ref(mat)) which do not rely on plausibility or pragmatics to disambiguate\deleted{d} the PP attachment sites, but instead make use of \added[id=TJP]{what will be referred to as} syntactic disambiguation by including a PP2 that cannot grammatically be incorporated into PP1\replaced{. This is illustrated}{, as} in (@syndis) and (@qsyndis). \added[id=TJP]{Syntactic disambiguation is the term chosen to refer to the sort of disambiguation used for the current study, although various terms could be used, e.g., lexical or semantic disambiguation; it hinges on the lexical identity of the preposition that heads PP2, i.e., \em{into} instead of \em{in} and what syntactic position or semantic role such a PP can be assigned.}

  (@syndis) He had planned to cram the paperwork [~PP1~ in the drawer] [~PP2~ into his briefcase].
\comment{added interrogative example}
  (@qsyndis) Had he planned to cram the paperwork [~PP1~ in the drawer] [~PP2~ into his briefcase]?
  
The change from pragmatic\deleted{ally} disambiguation \added{in} (@dec) and (@intr) to syntactic disambiguation \added{in} (@syndis) and (@qsyndis) creates an important distinction between the \replaced{hypothesis tested}{original observation} in @qp2 and \replaced{the hypothesis to be tested in}{what} the current study \deleted{is considering}. It cannot be assumed that the intuition about (@dec) \replaced{and}{vs.} (@intr) necessarily extends to cases like (@syndis)\added{and} (@qsyndis), and so one of the questions the current study \replaced{addresses}{asks} is whether the \replaced{greater ease of processing a question than a declarative}{intuition} can be shown to extend to syntactically disambiguated cases that are similar to the pragmatically disambiguated cases for which the observation was first made. In order to keep \added{a} clear \added{focus on} this \replaced{small}{fine} but \added{potentially} important difference, a convention \replaced{will be}{is} adopted throughout this document where the intuited amelioration of the garden path effect in pragmatically disambiguated cases is referred to as the 2016 Intuition, while the possibility that the intuition extends to syntactically disambiguated cases is referred to as the \replaced{C}{c}urrent \replaced{H}{h}ypothesis.

\comment{examples updated and pairs added}

  (@intui) *The 2016 Intuition:* Certain pragmatically disambiguated prepositional phrase (PP) attachment ambiguities which are difficult to parse in the declarative are less difficult to parse when presented as yes-no interrogatives (e.g., *The nanny sat the cranky little boy on the stroller on the swing*, vs., *Did the nanny seat the cranky little boy on the stroller on the swing?*).
  
  (@hypoi) *The Current Hypothesis:* The 2016 Intuition may be extensible to PP attachment ambiguities that are syntactically disambiguated in addition to those that are pragmatically disambiguated (e.g.,*He had planned to cram the paperwork in the drawer into his briefcase*, vs., *Had he planned to cram the paperwork in the drawer into his briefcase?*).

In addition to exploring the possible extensibility of the 2016 intuition, the current study \replaced{addresses}{is interested in} what property or properties of polar questions might lead to an easier parsing of garden paths, or at least to the perception that they are easier to parse when compared to declaratives. Because there are minimal differences between the polar question and \deleted{declarative version of} declarative versions of these sentences, it \replaced{seems likely}{is fairly easy to assume} that the cause lies in one of two domains: \added{either} the prosodic changes triggered by the use of question intonation, or the pragmatic and semantic properties that are not shared across the versions. 

An obvious reflex of the former possibility is another question: how are the various versions of these sentences actually pronounced, prosodically? \deleted{T}{t}he reported study seeks to answer \replaced{this}{it}, but while the recordings collected provide some insight, more work is likely needed to \deleted{satisfactorily} provide a\replaced{a fully satisfactory}{n} answer.

Likewise, the latter possibility \replaced{raises the question: exactly}{leads one to wonder:} what are the semantic and pragmatic differences between a polar question and its declarative counterpart? This question \replaced{has been}{can be} approach\added{ed} in \replaced{the}{a more} theoretical \deleted{way, and has been to some degree in the} literature \added{(see, e.g.} @fiengo \added{)}. \replaced{Nevertheless}{That said}, it remains to be determined how those properties could lead to an easier \added{or more difficult} parsing process\deleted{, and whether or not a satisfactory explanation for the intuition at large can be pulled from these differences}.}

## Structural overview of the ambiguity relevant to this study {#mech}

The 2016 \replaced{I}{i}ntuition and the current hypothesis are both concerned with a temporarily ambiguous sequence of PPs at the end of a sentence. This section will discuss what the possible attachment sites for those PPs are and which structures ultimately do and do not \replaced{prove viable}{work}.

The example in (@aa) shows a pragmatically disambiguated sentence with an argument-PP2. \deleted{The initial parse (a) is implausible, resulting in structural reanalysis to the preferable parse in (b).}

  (@aa) Jed crammed the newspapers under the sofa in the wastebasket. 
  a) $\#$ … [~VP~ crammed [~NP~ the newspapers] [~PP1~ under [~NP~ the sofa [~PP2~ in the wastebasket]]]\\
  b) $\checkmark$ … [~VP~ crammed [~NP~ the newspapers [~PP1~ under [~NP~ the sofa ]]  [~PP2~ in the wastebasket]]\\
    *"$\#$" indicates a structure with an implausible reading*

The initial parse is expected to be (@aa a) because of a bias (due to Minimal Attachment, or some variation thereof, see (@MinAtt) above), which favors a structure where the first PP attaches into the verb phrase (VP) as an argument of the verb, i.e., [~VP~ V NP PP1] \added{with PP1 denoting the goal}, which leaves nowhere for the second PP to attach but as a modifier of the noun phrase (NP) inside PP1 ([~PP1~ *under* [~NP~ *the sofa* [~PP2~ *in the wastebasket*]]]). This initial parse (@aa a) is pragmatically implausible, \replaced{since}{as one does not generally find} sofas \added{are generally not found} inside wastebaskets. Structural reanalysis is required to bring about the \replaced{only plausible}{correct} parse (@aa b), where PP1 attaches as an NP modifier of the direct object and so allows PP2 to attach as a VP argument, resulting in a structure such as [~VP~ V [~NP~ N PP1] PP2], i.e., where \deleted{it is} the newspapers under the sofa \deleted{that} are being crammed in\added{to} the wastebasket. 

\replaced{For clarity in what follows}{It is important to be clear on how the sentences of concerned are structured. As a matter of terminology}, the current study categorizes the sentence\added{ type}s being discussed into two groups based on the status of the PP2 they contain: (a) cases where PP2 is an argument \added{of the verb} are \added{referred to as} Arg-type sentences, and (b) cases where PP2 is a modifier \added{of the preceding noun} are \added{called} Mod-type sentences \added{; see} (@pp2t). \replaced{As noted, it is the}{In practice,} Arg sentences \added{that} are \added{generally reported to be} garden paths, because PP2 must fill the goal role that PP1 is expected to have filled as just discussed. Mod sentences are not \added{likely to result in a} garden path\deleted{s}, because PP2 can modify the NP within PP1 \replaced{to}{and} become part of the goal, and therefore need not disrupt PP1\replaced{'s attachment as}{ from being} the goal.

  (@pp2t) **PP2 attachment status**
    (a) *PP2 Argument* (Arg) \linebreak
    He had planned to cram the paperwork [~PP1~ in the drawer] [~PP2~ into his briefcase].
    (b) *PP2 Modifier* (Mod) \linebreak
    He had planned to cram the paperwork [~PP1~ in the drawer [~PP2~ of his filing cabinet]].

In order for the differing parsing process for (@pp2t a) and (@pp2t b) to be explained by a strictly structur\replaced{e}{ally} based model of parsing, certain assumptions have to be made about the syntax. A simple way to \replaced{achieve it}{get the explanation to work} is to assume that all arguments of a verb are syntactic sisters to the verb, resulting in a three-way branching VP for ditransitive verbs \added{such as \em{cram}}. In this case, in order to avoid postulating extra nodes that would be required for PP1 to be a modifier \added{of the object NP}, Minimal Attachment dictates that PP1 should be assumed to fill the \added{verb's goal} argument slot. \added{However,} \replaced{t}{T}his is not how \replaced{current}{modern} syntactic theory assumes the structure \replaced{to be}{looks}, as three-way branching is proscribed (see e.g., @chomsky2014minimalist). 

The most pronounced structural difference between the two structures is that in the sentence with a modifier-PP2 (Mod) the major disjuncture comes fairly early, just after the object NP *the newspapers*. For the sentences with argument-PP2s (Arg), the major disjuncture is later, just after PP1 (*under the sofa*). 

It bears mentioning that Minimal Attachment as defined by @Frazier1979-pb is somewhat at odds with recent developments in syntactic theory, e.g., obligatory binary branching [cf. @chomsky2014minimalist, p. 62]. As originally postulated, Minimal Attachment relies on a verb with multiple internal arguments incorporat\replaced[id=TJP]{ing}{es} each of those arguments as a sister (i.e., a ternary branching structure as in \@ref(fig:threetree)). 

\begin{figure}
  \centering
  \begin{forest}
    where n children=0{tier=word,font=\normalsize}{}
    \footnotesize
    [VP
      [V]
      [DP]
      [PP]
    ]
  \end{forest}
  \caption{Illustrative syntactic tree of a ternary-branching VP.}
  \label{fig:threetree}
\end{figure}

With\added{in} current theories of syntax\added{,} where binary branching is obligatory, two XPs (NP and PP) cannot both be syntactic sisters of the verb, and the structures are assumed to be as shown in \deleted{the trees presented earlier (}Figures \@ref(fig:modTree) and \@ref(fig:argTree) below[^trees]\replaced{,}{)} so it becomes less clear that the VP attachment site for PP1 actually creates fewer nodes than the lower NP attachment site\added{, as per Minimal Attachment}. Nonetheless, \replaced{studies by,}{the preference for VP attachment in these kinds of sentences is there, be it due to Minimal Attachment, a preference for arguments over non-arguments, or something else, as evidenced by experimental data from} e.g., @raynerEtAl1983, @cliftonEtAl1991, and others, \added[id=TJP]{show that a preference for VP attachment of a PP in contexts such as the one the current study addresses exists, whether that preference is best explained by Minimal Attachment, or a preference for arguments over non-arguments, or some other mechanism}.

[^trees]: Note that when the internal structure of an NP is not relevant (no PP is within it) it is not drawn in these figures, i.e., [NP newspapers] is shorthand for [NP [N' [N newspapers]]].

\begin{figure}[h!]
  \centering
  \begin{forest}
    where n children=0{tier=word,font=\normalsize}{}
    \footnotesize
    [\dots
      [VP 
        [V' 
          [V' 
            [V [cram]] 
            [DP 
              [D' 
                [D [the]] 
                [NP [newspapers]]
                ]
              ]
            ]
          ]
          [PP1$_{Arg}$
            [P' 
              [P [under]] 
              [DP 
                [D'
                  [D [the]] 
                  [NP
                    [N'
                      [N' [N [sofa]]]
                      [PP2$_{Mod}$
                        [P'
                          [P [from]] 
                          [DP 
                            [D' 
                              [D [the]] 
                              [NP [thrift store]]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]
  \end{forest}
  \caption{Syntactic tree of an illustrative example sentence with an ambiguous PP1 and a modifier-PP2 (Mod).}
  \label{fig:modTree}
\end{figure}

\begin{figure}[h!]
  \centering
  \begin{forest}
    where n children=0{tier=word,font=\normalsize}{}
    \footnotesize
    [\dots
      [VP 
        [V' 
          [V' 
            [V [cram]] 
            [DP 
              [D' 
                [D [the]] 
                [NP 
                  [N' 
                    [N [newspapers]]
                  ] 
                  [PP1$_{Mod}$ 
                    [P'
                      [P [under]] 
                      [DP 
                        [D' 
                          [D [the]] 
                          [NP [sofa]]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
          [PP2$_{Arg}$
            [P' 
              [P [into]] 
              [DP 
                [D'
                  [D [the]] 
                  [NP [wastebasket]]
                ]
              ]
            ]
          ]
        ]
      ]
    ]
  \end{forest}
  \caption{Syntactic tree of an illustrative example sentence with an ambiguous PP1 and an argument-PP2 (Arg).}
  \label{fig:argTree}
\end{figure}

\replaced{Setting}{Rather than worry about} the particularities of syntactic theory \replaced{aside now,}{and it also is not necessary to rely on Minimal Attachment}, an appeal can be made to a \added{psycho-linguistic} distinction added to parsing theory in *Construal* [@frazier1996construal]: that of primary vs. non-primary relations.  

  (@primrel) "Primary phrases and relations include 
    a) The subject and main predicate of any (+ or -) finite clause
    a) Complements and obligatory constituents of primary phrases"
  [@frazier1996construal, p. 41]

This additional \replaced{contrast}{machinery} is independently motivated: \replaced{Frazier and Clifton}{while structure-first decision making seems to hold for the parsing of many structures, there are some that seem to follow different rules. *Construal*} illustrate\deleted{s} this by way of relative clause (RC) attachment in constructions like (@rc).

  (@rc) The journalist interviewed [~NP1~ The daughter~i~] of [~NP2~ the colonel~j~] [~RC~ who~i/j~ had an accident] [@frazier1996construal, p. 71].

The RC in (@rc) can modify either NP1, *the daughter*, or NP2 *the colonel*. \deleted{A structure-first parsing system, together with the widely agreed upon structural parsing strategy} Late Closure\replaced{(see}{,} (@LateClo)\added{)} predict\added{s} a consistent preference for local attachment of the RC in (@rc), i.e., the structure where the RC modifies NP2. \added{This is because Late Closure dictates that the NP2 phrase not be closed until material that cannot, for one reason or another, be incorporated into that phrase is encountered. Since the RC can modify NP2, Late Closure predicts that it will.} Instead, what a number of empirical studies [e.g., @clifton1988restrictions; @Cuetos1988-tm] find is a pattern where the preferred structure depends on the relationship between NP1 and NP2. @frazier1996construal describe five categories of relationship, and a gradient of preferred RC attachment, from NP1 preference to NP2 preference.

  (@rcrel) __RC Attachment by NP1-NP2 relation__ [@frazier1996construal, p. 31]
      a) *Material* \linebreak
      The table of wood [~RC~ that was from Galicia]
      a) *Quantity* \linebreak
      The glass of wine [~RC~ you liked]
      a) *Relational* (friend, enemy, son, and other argument taking NPs, e.g., picture-NPs) \linebreak
      The son of the woman [~RC~ that was dying]
      a) *Possessive* \linebreak
      The car of the company [~RC~ that was falling apart]
      a) *Non-accompaniment* with \linebreak
      The girl with the hat [~RC~ that looked funny]

@frazier1996construal cite studies showing that (@rcrel a-b) type configurations favor NP1 RC attachment, (@rcrel e) type configurations favor NP2 RC attachment, while (@rcrel c-d) are intermediate. They argue that this gradient cannot be readily explained by structural parsing, and instead \added{they} make use of a mechanism they call association. RCs, rather than being immediately slotted into a tree in a specific way, are associated with a thematic domain, i.e., the maximal projection of whatever lexical item last assigned theta-roles, together with associated functional projections; in the case of the examples in (@rcrel), the last theta assigner is NP2, and its domain extends up to the DP that contains NP1. \replaced{Association}{This} is a later parsing decision that allows the syntactic structure to be decided after semantic information becomes available: the RC can ultimately modify whichever member of the thematic domain is appropriate. 

The \replaced{factor that determines when}{crucial issue that distinguishes cases where structural} association \replaced{or}{vs.} structural parsing is appropriate is the \replaced{distinction between}{idea of} primary vs. non-primary relations. Frazier and Clifton\added[id=TJP]{'s} formaliz\replaced[id=TJP]{ation of}{e} this distinction \added[id=TJP]{was previously mentioned} \replaced{as}{in} (@primrel) \added[id=TJP]{above}. \comment{Moved the formalization from here to above.}

RC attachment undergoes association because \added{relative clauses are by definition modifiers, and} the relationship between a modifier and whatever is modified is a non-primary relation\deleted{, and a relative clause is by definition a modifier and not an argument.} \replaced{Returning now}{Circling back} to the PP-attachment \added{construction} that this study is concerned with, the argument vs. modifier distinction is precisely what distinguishes the two possible \replaced{roles}{statuses} of PP2 shown \deleted{and illustrated} in (@pp2t)\replaced{,}{ and} repeated here as (@pp2tr).

  (@pp2tr) **PP2 types**
    (a) *PP2 Argument* (Arg)
    He had planned to cram the paperwork [~PP1~ in the drawer] [~PP2~ into his briefcase].
    (b) *PP2 Modifier* (Mod)
    He had planned to cram the paperwork [~PP1~ in the drawer [~PP2~ of his filing cabinet]].

\deleted{Without locking down the exact syntactic structures that (@pp2tr) represents, we can nonetheless say that the parser would seek to immediately incorporate PP1 into the tree in both cases.} The infinitival \deleted{(-finite)} clause headed by *cram* is a primary phrase, and so its obligatory constituents hold primary relationships with *cram*. \replaced{As such, association is not available as a mechanism and structural parsing must occur, without semantic information being available. Thus, PP1 is initially interpreted as the goal of \em{cram}.}{*Cram* takes an obligatory goal argument, so the parser cannot wait for semantic information to inform its association, it must make its best guess based on the principles of structural parsing, and attach it as an argument, as that property is what is forcing the immediate decision to be made.} \replaced{Then, i}{I}n the case of (@pp2tr a), when PP2 is encountered\replaced{, PP1 must be removed from its syntactic position and be reanalyzed as a modifier of the object NP in order to allow PP2 to fill the goal argument position}{ reanalysis of the PP1 attachment will be required, due to the fact that PP2 must be the goal of *cram* and therefore takes the syntactic position that PP1 had been filling}. In the case of (@pp2tr b), no reanalysis is necessary because PP2 can modify *the drawer* and so does not \added{need to} dislodge PP1.


## Interrogativity

This section returns to the questions raised by the 2016 \replaced{I}{i}ntuition discussed in Section \@ref(obs) about why certain \deleted{interrogative} garden paths of the sort just discussed might appear to be easier to parse \replaced{in interrogative constructions than in otherwise}{than} similar declarative ones \added{(see examples} (@d) and (@q) \added{)}.

\comment[id=TJP]{on second thought, I think these need to stay}
  (@d) He had planned to cram the paperwork [~PP1~ in the drawer] [~PP2~ in his briefcase].
  (@q) Had he planned to cram the paperwork [~PP1~ in the drawer] [~PP2~ in his briefcase]?

\replaced{W}{Specifically, w}hat exactly differs between (@d) and (@q)? Syntactically, very little: the position of the subject *he* and the auxiliary *had* have been reversed\added{, but the words that follow are identical}.

The semantic, or perhaps more accurately pragmatic, differences between (@d) and (@q) lie with the presuppositions the sentences carry with them, \replaced{which may vary}{and} with the placement of focus\added{, marked phonologically in spoken language}. \added[id=TJP]{The exact phonetic properties of focus, and the semantic and syntactic consequences of it, are widely studied and debated. For an excellent overview of the topic, see} @ladd, pp.213-23\added[id=TJP]{. The assumptions made about focus in this dissertation are about English only, and are more or less compatible with a Focus-to-Accent model as described by Ladd, which distinguishes "the semantic/pragmatic notion 'focus' from the phonetic/phonological notion 'accent' and -- crucially -- [...] allows focus to apply to portions of utterances larger than individual words"} [@ladd p. 217]\added{. This results in sentential stress being split into two related but independent components: where focus lies within the sentence, and how it is conveyed with regard to the location of accent.}

The declarative in (@d) has few presuppositions beyond the existence of the actors and objects involved (the referents of *he*, *paperwork*, *drawer* and *briefcase*), and that these actors and objects can be involved in *cramming*. The presuppositions of (@q) are \replaced{different from}{a super set of} those of (@d): \added{for instance,} a yes/no question additionally presupposes that the listener \added{does or may} know\deleted{s} the answer to the question\replaced{.}{, for one,} \added{and also may not presuppose the referent of a focused element. Further presuppositions \replaced{may}{might} exist, depending on where the focus lies within the sentence. 

Focus in a declarative like (@d) is typically \replaced[id=TJP]{wide}{broad}, \replaced{i.e.,}{meaning} no element is having \added[id=TJP]{special} attention called to it. A polar question like (@q), however, will \replaced{often}{typically} receive narrow\added[id=TJP]{er} focus on one \replaced[id=TJP]{word or phrase}{element}, so that when uttered, \replaced{that}{one} \replaced[id=TJP]{word or phrase}{element} is more prominent than the others. The focused element becomes the part of the sentence that the question is about. Focus can fall on any of the lexical or referential elements \added{in the sentence} (subject, auxiliary verb, matrix verb, infinitival verb, object NP, or the NP of either PP1 or PP2) \replaced{or any part of one of these}{of the sentence, or the auxiliary verb}. \replaced{Words in all capital letters indicates verbal emphasis signifying focus.}{Bold facing indicates verbal emphasis in order to locate focus}

\singlespacing
  (@foc1) HAD he planned to cram the paperwork [~PP1~ in the drawer] [~PP2~ into his briefcase]?
  (@foc2) Had HE planned to cram the paperwork [~PP1~ in the drawer] [~PP2~ into his briefcase]?
  (@foc3) Had he PLANNED to cram the paperwork [~PP1~ in the drawer] [~PP2~ into his briefcase]?
  (@foc4) Had he planned to CRAM the paperwork [~PP1~ in the drawer] [~PP2~ into his briefcase]?
  (@foc5) Had he planned to cram the PAPERWORK [~PP1~ in the drawer] [~PP2~ into his briefcase]?
  (@foc6) Had he planned to cram the paperwork [~PP1~ in the DRAWER] [~PP2~ into his briefcase]?
  (@foc7) Had he planned to cram the paperwork [~PP1~ in the drawer] [~PP2~ into HIS briefcase]?
  (@foc8) Had he planned to cram the paperwork [~PP1~ in the drawer] [~PP2~ into his BRIEFCASE]?
  
\doublespacing
  
In (@foc1), with focus on the auxiliary, the question \replaced{encompasses}{is about} the entire proposition, and \added{asks} whether or not it is true. In this case, there are not any additional presuppositions when compared to the declarative counterpart of the sentence. In (@foc2), with focus on *he*, the question is asking about whether the referent of *he* is the actor who performed the action described; in this case, the entire predicate is presupposed: someone *had planned to cram the paper in the drawer into his briefcase*, but was it *him*? \replaced{In}{Skipping ahead to} (@foc6), with focus on *drawer*, the question is instead about which paperwork this is all happening to: the paperwork that is in the drawer, or some other stack of paperwork? In this case, it is presupposed that the referent of *he* was the one who had planned to cram some paperwork into his briefcase, and only the exact referent of *the paperwork* is not presupposed. For each other location of focus, the Presuppositional content is similarly complementary to whichever element is focused and therefore being asked about. 

This set of pragmatic differences between (@d) and (@q) might \deleted{very well} be the source of the 2016 Intuition that (@q) is easier to comprehend than (@d), but \replaced{it is not entirely clear why, and it}{that} is not the only possibility. Another significant difference between the two \replaced{sentences}{Speech Acts} is the \replaced{rhythm}{prosody} and intonational melody \added[id=TJP]{(which, taken together, make up the prosody)}. While dialects of English \added{may} differ \added{prosodically}, there is typically a difference in melody between a declarative and \added{a} question, and in many American English dialects, the interrogative is pronounced with a final rise, while the declarative exhibits just a series of down-steps. This difference is the one that the current study explores, to see if it can \replaced{be shown to correlate with a difference in processing difficulty in syntactically disambiguate declarative and interrogative PP-attachment garden paths, and by extension lend insight into the 2016 Intuition}{readily explain the intuitive difference in processing difficulty}.


## Prosody of questions vs. declaratives

In pursuing the possibility that it is the \deleted{intonation and} prosody of polar interrogatives which creates the 2016 \replaced{I}{i}ntuition that motivated this study \replaced{it is important to}{we must} consider \replaced{the details of}{what} question intonation actually sounds like. It is generally agreed that in American English, the intonation of a polar question has \replaced{exhibits}{the property of} a final rise. \replaced{T}{Indeed, t}his has been confirmed in corpus studies such as @Hedberg2017-er who found that 79.8% of the 410 American English yes/no questions in their study (ten-minute phone conversations from  the CallHome Corpus of American English and the Fisher English Corpus) had a &ldquo;low-rise nuclear contour&rdquo; (L\*H-H%, L\*H-$\uparrow$H%, or L\*L-H%)[^uar]. In their ToBI notation, a tone T is \added{coded} either L for low or H for high; T\* is anchored to the stressed syllable, and T- and T% are boundary tones (intermediate phrase boundary and intonational phrase boundary respectively). See\deleted{, e.g.,} *Guidelines for ToBI labeling* [@Beckman1997-eu] for a more thorough explanation of ToBI. An additional 10.7% of the @Hedberg2017-er data had a &ldquo;high-rise nuclear contour&rdquo; (the authors categorize\deleted{s} the following tunes as high-rise nuclear contours: H\*H-H%, or !H\*L-L%). That leaves only 9.5% spread across the other 5 categories (High-fall, Rise-fall, Low-fall, Fall-rise, and Level). Only 5.6% of the \added{total} data showed a\added{ny sort of} falling contour. According to the authors' analyses, \replaced{final high-rise}{these} contours occur on the final main stress of a sentence and thereafter. In the case of the types of sentences examined in the current study, that would result in a rising contour on the head noun of the final PP as in (@rise)\added{, regardless of whether the final PP is a Mod or an Arg}.

[^uar]: @Hedberg2017-er use $\uparrow$ to indicate an up-step, which is not standardly transcribed with ToBI.

  (@rise) Did Jed cram the newspapers under the sofa in the	[~L\*H-H%~ guestroom].

The need to prepare for that final rising tone might make a prosodic break before the PP more likely, and thus ease reanalysis or even encourage a different prosodic chunking which might encourage argument attachment. This \deleted{is} possibility is revisited and more fully explained in Section \@ref(prep).

The prosodic structures \replaced{observed}{found} in the data collected for the current study are discussed in \@ref(results-prosody). \comment{This has been moved up} For discussion of what constitutes a prosodic boundary, see e.g., @streeter1978acoustic and @salverda2003role. 


## Evidence that prosody can affect syntactic parsing
\comment{Section title has been updated}

A number of studies have shown that in listening to speech, prosodic cues \deleted{appear to} help reduce the frequency with which incorrect parsing (i.e., a garden path) occurs. For example, @Kjelgaard1999-xd conducted a study using digital manipulation of  recorded speech to create three versions of sentences containing a temporary ambiguity which could result in a garden path. They recorded speakers saying sentences with natural prosody, such as the following pair (not bracketed in presentation to the \replaced{speakers}{participants}):

  (@ec) [When Roger leaves] the house is dark. (Early closure)
  (@lc)	[When Roger leaves the house] it's dark. (Late closure)
  
They then cross-spliced these together to make several versions. One version had prosodic cues which cooperated with the intended reading of the sentence; another attempted to have &ldquo;neutral&rdquo; prosody; and the third used intentionally misleading prosody\added{ which favored the garden path}. The initial fragment of each \added{(the portion from the beginning of the sentence to the word \em{house} in}(@ec - @lc)\added{)} was then presented to participants \replaced{who}{(the portion from the beginning of the sentence to the word *house* in (@ec - @lc) and they} were asked to agree or disagree with whether a visually presented word, either *is* or *it's* was likely to be the next word in the sentence. Participants gave more accurate and speedier judgments \replaced{when the visually presented word was compatible with the structure indicated by the prosodic cues}{when the prosodic cues lined up with the correct parsing}. The results of this study, as well as a growing body of literature, suggest that \deleted{that} prosodic information can \added{indeed} be used by the parser in making processing decisions.

\deleted{Consider the analysis by} @Fodor2002-io \replaced{invoked prosody in an explanation of differing relative clause attachment preferences}{of relative clause attachment preferences in English} \deleted{an example of the differing RC attachment preferences} across languages \added{first} pointed out by @frazier1996construal and discussed \added{above} in Section \@ref(mech). This concerns sentences such as English (@servant) \added{and Spanish} (@esprc):

  (@servant) Someone shot the servant~N1~ of the actress~N2~ [~RC~ who was on the balcony].
  (@esprc) Alguien disparó contra la criada de la actriz que estaba en el balcón.

The relative clause \replaced{in}{(RC)} (@servant) *who was on the balcony*\added{,} can attach either locally (modifying N2), making it *the actress* who was *on the balcony*, or non-locally (so that it is *the servant* who was *on the balcony*. While Late Closure predicts local/low attachment in these \replaced{structures}{sorts of sentences}, @Cuetos1988-tm found a 60% preference for local/low attachment \replaced{for the}{in} English \replaced{materials}{speakers}, but only a 40% preference for local/low attachment in Spanish \deleted{speakers}. In apparent violation of the general preference for local/low attachment, some languages, like Spanish (and French and Russian, but not Romanian or Brazilian Portuguese, so this is not a general feature \replaced{exclusive to}{of} Romance languages), prefer to attach relative clauses higher, while others more often obey Late Closure \added{as in English} (e.g., Swedish\replaced{ and}{,} Egyptian Arabic\deleted{, and English}). \replaced{Interestingly, the}{This} non-local preference \added{in languages like Spanish} is weakened in cases where the ambiguous RC is short (one prosodic word)\added{, which is compatible with its being attributable to prosodic phrasing; see below)}. @Fodor2002-io \replaced{maintains}{asserts} that these tendencies exist both in listening to spoken \replaced{sentences, with and without}{words (under conditions where a particular parse is not favored by the} explicit prosody\deleted{)} and in silent reading.

\replaced{O}{Fodor notes that o}ther researchers, \added{e.g.,} @maynell1999effect, have shown that the presence \added{or absence} of a prosodic break before \replaced{an}{the} RC \deleted{in sentences like (@servant)} encourages high \added{or low} attachment \added{respectively}. Fodor leverages this in order to explain the difference\added{s} in RC attachment site tendency between languages. She argues that the \replaced{cross-language differences}{phenomenon} can be neatly \replaced[id=TJP]{explained}{account for} by linking attachment site preference to the likelihood of a prosodic break before the RC. This difference in prosodic tendency, in turn, can be explained using a constraint\deleted{s}-based approach. Consider Selkirk's [-@Selkirk1986-hc] alignment constraints:

  (@align) Align($\alpha$Cat, E; $\beta$Cat, E)
    a. Align (GCat, E; PCat, E)
    b. Align (PCat, E; GCat, E) 
    c. Align (PCat, E; PCat, E)\\
    *GCat ranges over morphological and syntactic categories; PCat ranges over prosodic categories; E = Right or Left [@Selkirk1986-hc, p. 6]*


@Truckenbrodt1999-vd provides a prose-based formalization of \replaced{this general}{the same} idea \added{for English}. 

  (@alignxp) **Align-XP/R** \linebreak
  For each XP there is a PP such that the right edge of the XP coincides with the right edge of the PP, where XP is a maximal projection and PP is a Phonological Phrase. This constraint represents the end based mapping assumption for Major Phonological Phrases in English, whose right end is supposed to align with the right end of Maximal Projections [@Truckenbrodt1999-vd, p. 223].

\deleted{Essentially, @Fodor2002-io argues that} \replaced{The}{relative} ranking of alignment constraints for the left edge of phrases (*Align-XP/L*) with those for the right edge of phrases (*Align-XP/R*) can impact the distribution of prosodic breaks. These alignment constraints dictate that the edges of prosodic units (and thus the location of prosodic breaks) should align with the edges of syntactic constituents. Because the prosodic break that encourages high attachment \deleted{is one which} aligns with the left edge of the RC in examples like (@esprc), \deleted{postulating that} *Align-XP/L* is \added{postulated to be} ranked above *Align-XP/R* in languages like \replaced{Spanish}{French} that prefer high attachment \replaced{since}{can account for that preference (remember that} a prosodic break in that place has been shown to encourage a high attachment interpretation\deleted{)} [@maynell1999effect]. In languages where low RC attachment is preferred, \deleted{we can assume that} *Align-XP/R* \replaced{can be postulated to be}{is} ranked higher, and thus a prosodic break is more likely to occur after the RC than before \added{it}.

The same sort of argument can explain the difference in tendency between long and short RCs. Consider Selkirk's [-@selkirk2011-hp] *BinMin* defined below.

  (@binmin)	**BinMin($\phi$)** \linebreak
  A $\phi$ (phonological phrase) must consist of at least two $\omega$ (phonological words).  
  
If \deleted{we assume}, in Optimality Theoretic [@Prince1993-ic] terms, \deleted{that} a constraint like *BinMin* is ranked above *Align~L~*, then it seems quite reasonable to assume that  a prosodic break before a short RC (which would encourage high attachment) is much less likely than before a long RC. That is, when the RC is short, its left edge is prevented from aligning with the beginning of a prosodic phrase (it violates *Align~L~*) by the higher ranked BinMin\added{, because it needs more material in order to achieve a length of at least two phonological words, and so must borrow some for the preceding NP. Longer RCs can have their left edge align with the start of a prosodic phrase, and thus can have the high-attachment encouraging prosodic break\added{, because they have enough phonological content to stand alone}.


## Predictions for the current study
\comment{not all changes to this section are well represented by annotation; we should read it together}
\replaced{The experimental study presented here addresses}{This study is concerned with} a number of issues. First: is \added{syntactic phrase} attachment in any way encoded in the speech signal? I hypothesize, following e.g., @schafer2000intonational \added{as noted above that it is, and therefore} that \deleted{we can use} prosody \added{can be used} to diagnose attachment site. Consider the basic configuration in Figures \@ref(fig:smallmod) and \@ref(fig:smallarg) \added{below}.


\begin{figure}[h!]
  \centering
  \begin{minipage}{0.45\textwidth}
      \centering
      \begin{forest}
        where n children=0{tier=word,font=\normalsize}{}
        \footnotesize
        [S
          [NP$_{SUBJ}$]
          [VP
            [V'
              [V' 
                [V]
                [N$_{OBJ}$]
              ]
              [PP1
                [NP$_{OBJ}$
                  [N$_{OBJ}$]
                  [PP2]
                ]
              ]
            ]
          ]
        ]
      \end{forest}
      \caption{Illustrative syntactic tree of the basic configuration for Mod cases.}
      \label{fig:smallmod}
  \end{minipage}\hfill
  \begin{minipage}{0.45\textwidth}
      \centering
      \begin{forest}
        where n children=0{tier=word,font=\normalsize}{}
        \footnotesize
        [S
          [NP$_{SUBJ}$]
          [VP
            [V'
              [V' 
                [V]
                [NP$_{OBJ}$
                  [N$_{OBJ}$]
                  [PP1]
                ]
              ]
              [PP2]
            ]
          ]
        ]
      \end{forest}
      \caption{Illustrative syntactic tree of the basic configuration for Arg cases.}
      \label{fig:smallarg}
  \end{minipage}
\end{figure}

\replaced[id=TJP]{The predictions made here rely on there being an ideal prosodic structure for the sentences tested to compare them with. Following @Fodor2002-io, a major disruption to the syntax like the one after PP1,}{I suggest that argument attachment of PP2} \added{as in Figure} \@ref(fig:smallarg), \replaced{should}{will} be marked by a prosodic boundary between PP1 and PP2. \replaced{On the other hand, m}{M}odifier attachment of PP2\deleted{, on the other hand,} will lack any substantial boundary marking in that position \added{unless it is necessitated for length reasons}; instead, a break after the object is expected.

  *Running assumption about syntax-to-prosody mapping* 
  Argument attachment of PP2 is marked by a dominant prosodic break between PP1 and PP2.

\replaced{An}{The second} issue \replaced{that is addressed is}{:} what factors impact immediate on-line parsing, and what factors only affect later, post-parse considerations? To address this, the study will employ the double reading paradigm of @fodor2019center (more on double reading in the methods section). For example, if first-pass parsing ignores semantic information, then \added{semantically} implausible parses should be more frequent in Reading 1 of a sentence with argument-PP2 than in a second reading of the same sentence.

  (@hypb) *Hypothesis 1*
  A first reading of a sentence where PP2 is a goal argument (Arg) will exhibit less natural prosody (more hesitation at and within the PP2 region) than:
    a. A first reading of a sentence where PP2 is a modifier (Mod)
    b. A second reading of a sentence where PP2 is a goal argument (Arg)
    
  (@hypd) *Hypothesis 2*
  A first reading of a sentence where PP2 is a goal argument (Arg) will more often be produced with prosodic structure that represents an implausible or ungrammatical parse of the string (PP2 incorrectly attached as a modifier), whereas a second reading of that sentence will more often be pronounced with the prosodic structure that represents the intended parse (argument attachment of PP2).

*Hypotheses 1* and *2* together make a third prediction: readers should struggle more on the cold reading of a sentence with an argument PP2 (Arg) to obtain a plausible structure, and thus the appropriate prosody, than on a \replaced{second}{previewed} reading.

  (@hype) *Hypothesis 3* 
  Reading 1 of a declarative sentence with an argument-PP2 will exhibit less natural prosody (more hesitation at and after the disambiguating region) and be more likely to be produced with prosodic structure that represents an implausible or ungrammatical parse of the string than a Reading 1 of an interrogative sentence with an argument-PP2.
  
Finally, the question of whether the 2016 Intuition described in Section \@ref(obs) can be shown to extend to the syntactically disambiguated sentences \replaced{tested in the present}{used in this} study is \replaced{formalized as}{returned to with} *hypothesis 4*. \added{This hypothesis presumes that IRT reflects processing difficulty.}

  \comment{this is new}
  (@hypd) *Hypothesis 4*
  The inter-reading time (IRT) will be longer for Arg sentences that are declarative than for:
    a. Arg sentences that are interrogative
    b. Mod sentence that are interrogative or declarative

Note that \replaced{these hypotheses are not applicable}{*hypothesis 3* can’t be applied} in cases where the reader fails to successfully and fluently produce the sentence. 

These hypotheses are returned to in Chapter \@ref(res). The findings \added{from the current study that will be} presented \replaced{in what follows}{in the current study} do not successfully settle all of the issues raised here, but it is hoped that they \added{will} help guide future work in directions that may do so.

