---
bibliography: refs.bib
output: 
  bookdown::html_document2: 
    toc: true
---
# Discussion

This section will go through the motivating questions behind this study and discuss the extent to which those questions are answered, or not. It will discuss the issues that may have lead to some results that were disatisfying and how to correc them for futuer work. It will then go on to present further questions and propose further studies to explore those new questions and the ones left unanswered here.

## Behavioral evidence for the intuition

Ultimately the data here are unable to provide a clear answer to whether or not IRT represents a behavioral correlate of the intuition that PP-attachment garden paths are rendered easier to parse when presented as polar questions. While the mean IRT by condition shows a difference of 0.04s in the direction predicted by the intuition, this is a rather small difference when the grand mean is 

## Interpreting the results

It seems likely that the intuition is born out by IRT, as the means align with the intuition. The lack of statistical significance is likely due to a lack of statistical power, i.e. not enough data.

## Explaining the intuition

A possible explanation for the intuitive effect of ±Q on ±GP is provided in the work by Markus Bader (1998). Bader demonstrates that it is easier to recover a parse that “behave[s] alike prosodically” to a given failed parse, because the reanalysis does not require prosodic reconstruction and only the syntax needs to be repaired. In the case of the intuition this study is concerned with, this would mean that sentences should be more similar across the garden path vs. non-garden path condition in the interrogative than in the declarative. 

`r if (knitr::is_html_output()) '# References {-}'`

