library(readr)
library(lme4)
adata <- read_csv("../drafts/export/prosody_with_r1delcat.csv")
adata_nonorm <- subset(adata,r1DelCat != "NORMAL")
delcatpdom <- glmer(odom ~ Condition_GP * Condition_Q * Reading * r1DelCat + (1|Participant) + (1|IID),data=adata_nonorm,family="binomial")
summary(delcatpdom)
delcatpdom2 <- glmer(odom ~ Condition_GP * Condition_Q * r1DelCat + (1|Participant) + (1|IID),data=adata_nonorm,family="binomial")
summary(delcatpdom2)
delcatpdom3 <- glmer(odom ~ Condition_GP * r1DelCat + (1|Participant) + (1|IID),data=adata_nonorm,family="binomial")
summary(delcatpdom3)
delcatpdom4 <- glmer(odom ~ Condition_GP * r1DelCat + (1|Participant) + (1|IID),data=adata_nonorm,family="binomial")
delcatpdom5 <- glmer(odom ~ Condition_GP + r1DelCat + (1|Participant) + (1|IID),data=adata_nonorm,family="binomial")
summary(delcatpdom5)
delcatpdom6 <- glmer(odom ~ Condition_GP + (1|Participant) + (1|IID),data=adata_nonorm,family="binomial")
anova(delcatpdom5,delcatpdom6)

adata_nonorm <- subset(adata,r1DelCat != "NORMAL")
delcatpdom <- glmer(pdom ~ Condition_GP * Condition_Q * Reading * r1DelCat + (1|Participant) + (1|IID),data=adata_nonorm,family="binomial")
summary(delcatpdom)
delcatpdom2 <- glmer(pdom ~ Condition_GP * Condition_Q * r1DelCat + (1|Participant) + (1|IID),data=adata_nonorm,family="binomial")
summary(delcatpdom2)
delcatpdom3 <- glmer(pdom ~ Condition_GP * r1DelCat + (1|Participant) + (1|IID),data=adata_nonorm,family="binomial")
summary(delcatpdom3)
delcatpdom4 <- glmer(pdom ~ Condition_GP * r1DelCat + (1|Participant) + (1|IID),data=adata_nonorm,family="binomial")
delcatpdom5 <- glmer(pdom ~ Condition_GP + r1DelCat + (1|Participant) + (1|IID),data=adata_nonorm,family="binomial")
summary(delcatpdom5)
delcatpdom6 <- glmer(pdom ~ Condition_GP + (1|Participant) + (1|IID),data=adata_nonorm,family="binomial")
anova(delcatpdom5,delcatpdom6)
